### ISSUE TITLE
Getting missing assembly when DllExport for Delphi

### ISSUE THREAD

**Issue by wongmalesan** [googleads/google-ads-dotnet#258] opened 2020-12-10 07:26 UTC
Hello,

I have try to build class library with newest google ads api .NET library for my delphi project, but i always getting error **Could not load file or assembly 'Google.Apis.Auth, Version=1.46.0.0.**

what i do :
1. I create some procedure which i need in my Delphi app
2. I export my c# dll with ExportDLL nuget
3. I debug test on my dll with My Delphi app as Start External Program
4. Always geting error when hit this process 
**GoogleAdsServiceClient googleAdsServiceClient = client.GetService(Services.V6.GoogleAdsService);**

is google ads library use google.apis.auth with multiple version? can you help me how to solve this?

Thanks,
Regards

**Comment by AnashOommen** [comment] 2020-12-28 20:20
Hi,

Google.Ads.GoogleAds doesn't use Google.Apis.Auth directly. There's indirect dependency like:

Google.Ads.GoogleAds 6.1.0 > Google.Api.Gax.Grpc 3.2.0 > Google.Apis.Auth (>= 1.48.0 && < 2.0.0)
Google.Ads.GoogleAds 6.1.0 > Google.Api.Gax.Grpc 3.2.0 > Grpc.Auth 2.34.0 > Google.Apis.Auth (>= 1.46.0)

Adding a direct dependency on Google.Apis.Auth 1.48.0 should solve your issues. I'll ask the team to take a look.

**Comment by jskeet** [comment] 2020-12-29 08:21
I have no experience with Delphi. Is this Delphi *running* on the CLR, or does it have an interop layer somewhere? If it's running on the CLR, does it have NuGet package integration? If it does, I'd expect you to just be able to add a dependency on Google.Ads.GoogleAds 6.1.0 as well as your DLL, and everything should be fine due to the indirect dependencies.

If you could give us more details about your Delphi environment so we could reproduce the issue, that would really help.

**Comment by AnashOommen** [comment] 2020-12-29 13:48
Does the code in C# procedure work fine if you call it from another C# application?

**Comment by jtattermusch** [comment] 2021-01-08 14:55
I worked with Delphi about ~20 years ago in the very beginning of my programming career but frankly I don't see what does it have to do with C#/.NET since AFAIK Delphi uses Pascal programming language - so I suspect using the ads client library from Delphi is not something that's supported.

**Comment by AnashOommen** [comment] 2021-04-14 12:10
I'm closing this bug as not feasible.

**Closed by AnashOommen** 2021-04-14 12:10 UTC
