### ISSUE TITLE
In version 12.1.0 getting Method not found exception

### ISSUE THREAD

**Issue by Azami1002** [googleads/google-ads-dotnet#414] opened 2022-06-17 09:05 UTC
Same code is working with version 11.0 but yesterday i updated to version 12.0 after that i'm getting below error 
"Method not found: 'Void Google.Api.Gax.Grpc.ClientHelper..ctor(Google.Api.Gax.Grpc.ServiceSettingsBase)'."

           GoogleAdsClient client = new GoogleAdsClient();
            List<CampaignSetting> Campaign = new List<CampaignSetting>();
            **GoogleAdsServiceClient googleAdsService = client.GetService(Services.V11.GoogleAdsService);**

**Comment by AnashOommen** [comment] 2022-06-17 14:08
Hi,

I need a demo project to help me replicate this. I tried with a few combinations of project types, but no luck.

**Comment by AnashOommen** [comment] 2022-06-28 14:44
Duplicate of #416

**Closed by AnashOommen** 2022-06-28 14:44 UTC
Labels: bug
