### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by scamner** [googleads/google-ads-dotnet#416] opened 2022-06-20 13:38 UTC
I keep trying to use the version 11 library to connect to Google Ads API, but I keep getting this error. I am running it from my laptop at home, so wide open internet. I got my permanent Google OAuth 2 client ID and secret that I added to my app.config, but I keep getting the below.

Grpc.Core.RpcException: 'Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1655732174.917000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1655732174.917000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")'

**Comment by scamner** [comment] 2022-06-20 15:02
So, I upgraded to version 12.1.0 of Google.Ads.GoogleAds and the above error went away, but now I get....

Method not found: 'Void Google.Api.Gax.Grpc.ClientHelper..ctor(Google.Api.Gax.Grpc.ServiceSettingsBase)'.

**Comment by AnashOommen** [comment] 2022-06-22 17:34
Could you try adding a dependency to `Google.Ads.Gax` package? It should have been pulled directly because it is a dependency to Google.Ads.GoogleAds, but perhaps there's something weird going on...

**Comment by scamner** [comment] 2022-06-22 22:00
Google.Ads.Gax is added to the project.

Here is the main page that I am running. I tried to zip and send the project, but it's too big even minimally and I do not have it in github.

using Google.Ads.GoogleAds;
using Google.Ads.GoogleAds.Lib;
using Google.Ads.GoogleAds.Util;
using Google.Ads.GoogleAds.V11.Errors;
using Google.Ads.GoogleAds.V11.Services;
using System;

namespace SendCallData
{
    class Program
    {
        static void Main(string[] args)
        {
            GoogleAdsClient client = new GoogleAdsClient();
            TraceUtilities.Configure(TraceUtilities.DETAILED_REQUEST_LOGS_SOURCE,
    "C:\\test\\logs\\details.log", System.Diagnostics.SourceLevels.All);

            Run(client, 7043240301, "+18553150446", "2022-01-27 03:48:53 +0:00", "2022-01-19 10:36:37 -4:00", 15, null, null);
        }

        static void Run(GoogleAdsClient client, long customerId, string callerId, string callStartTime, string conversionTime, double conversionValue,
            long? conversionCustomVariableId, string conversionCustomVariableValue)
        {
            // Get the ConversionUploadService.
            ConversionUploadServiceClient conversionUploadService = client.GetService(Services.V11.ConversionUploadService);

            // Create a call conversion by specifying currency as USD.
            CallConversion callConversion = new CallConversion()
            {
                CallerId = callerId,
                CallStartDateTime = callStartTime,
                ConversionDateTime = conversionTime,
                ConversionValue = conversionValue,
                CurrencyCode = "USD"
            };

            if (conversionCustomVariableId != null &&
                !string.IsNullOrEmpty(conversionCustomVariableValue))
            {
                callConversion.CustomVariables.Add(new CustomVariable()
                {
                    ConversionCustomVariable = ResourceNames.ConversionCustomVariable(
                        customerId, conversionCustomVariableId.Value),
                    Value = conversionCustomVariableValue
                });
            }

            UploadCallConversionsRequest request = new UploadCallConversionsRequest()
            {
                CustomerId = customerId.ToString(),
                Conversions = { callConversion },
                PartialFailure = true
            };

            try
            {
                // Issues a request to upload the call conversion. The partialFailure parameter
                // is set to true, and validateOnly parameter to false as required by this method
                // call.
                UploadCallConversionsResponse response = conversionUploadService.UploadCallConversions(request);

                // Prints the result.
                CallConversionResult uploadedCallConversion = response.Results[0];
                Console.WriteLine($"Uploaded call conversion that occurred at " +
                    $"'{uploadedCallConversion.CallStartDateTime}' for caller ID " +
                    $"'{uploadedCallConversion.CallerId}' to the conversion action with " +
                    $"resource name '{uploadedCallConversion.ConversionAction}'.");
            }
            catch (GoogleAdsException e)
            {
                Console.WriteLine("Failure:");
                Console.WriteLine($"Message: {e.Message}");
                Console.WriteLine($"Failure: {e.Failure}");
                Console.WriteLine($"Request ID: {e.RequestId}");
                throw;
            }
        }
    }
}

**Comment by scamner** [comment] 2022-06-22 22:14
Also, the error happens on this line...

ConversionUploadServiceClient conversionUploadService = client.GetService(Services.V11.ConversionUploadService);

**Comment by scamner** [comment] 2022-06-27 11:12
Any progress on the above?

**Comment by AnashOommen** [comment] 2022-06-27 11:40
Could you perhaps delete the bin and obj folders? And the contents of the package folders? I can do a `dotnet restore` to generate those contents.

**Comment by scamner** [comment] 2022-06-27 12:18
I will get he bon and obj cleanup done and try again in a bit. I am using VS 2019 Enterprise and this project is a console app using .NET 4.7.2.

**Comment by scamner** [comment] 2022-06-27 12:21
I cleared the bin and obj and still get the same error.

**Comment by AnashOommen** [comment] 2022-06-28 14:57
I've attached a demo project. This is made in Visual Studio 2022 Community Edition, and is a Console project that targets .NET 4.7.2.

To run,

1. Unzip into a folder (e.g. `C:\Temp`)
2. `C:\> cd C:\Temp\ResolveDeps\ResolveDeps`
3. `C:\Temp\ResolveDeps\ResolveDeps> nuget restore -SolutionDirectory .. ResolveDeps.csproj`
4. Fill up the contents of `App.config`
5. Set your customerId in `Program.cs`.
6. `C:\Temp\ResolveDeps\ResolveDeps> msbuild ResolveDeps.csproj`
7. `C:\Temp\ResolveDeps\ResolveDeps> .\bin\Debug\ResolveDeps.exe`

Let me know if this reproduces the issue at your end. Then compare it with the csproj that you created at your end and let me know how they differ.
 
[ResolveDeps.zip](https://github.com/googleads/google-ads-dotnet/files/9002079/ResolveDeps.zip)

**Comment by AnashOommen** [comment] 2022-06-28 19:21
How does your directory structure look like? Which directory are you running commands from?

**Comment by scamner** [comment] 2022-06-28 19:50
So, basically I unzipped the project to my desktop. Is there something I need to install on the computer or something?

**Comment by AnashOommen** [comment] 2022-06-30 00:27
I was able to obtain a failing project from another source. tl;dr; you need to downgrade the following dependencies
```xml
  <package id="Google.Api.Gax" version="4.0.0" targetFramework="net472" />
  <package id="Google.Api.Gax.Grpc" version="4.0.0" targetFramework="net472" />
  <package id="Google.Api.Gax.Rest" version="4.0.0" targetFramework="net472" />
  <package id="Google.LongRunning" version="3.0.0" targetFramework="net472" />
```
to
```xml
  <package id="Google.Api.Gax" version="3.7.0" targetFramework="net472" />
  <package id="Google.Api.Gax.Grpc" version="3.7.0" targetFramework="net472" />
  <package id="Google.Api.Gax.Rest" version="3.7.0" targetFramework="net472" />
  <package id="Google.LongRunning" version="2.3.0" targetFramework="net472" />
```
Make sure you also do this in your `App.config` just in case Visual Studio doesn't automatically do it for you. A typical binding redirect looks like this:
```xml
<dependentAssembly>
  <assemblyIdentity name="Google.Api.Gax" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-3.7.0.0" newVersion="3.7.0.0" />
</dependentAssembly>
```

The longer explanation is that `Google.Api.Gax` did a refactoring recently to choose between [`Grpc.Core`](https://www.nuget.org/packages/Grpc.Core) (on .NET 472) and [`Grpc.Net.Client`](https://www.nuget.org/packages/Grpc.Net.Client) (on .NET 5+/.NET Standard 2.0+). This is backwards-incompatible, so the team did a major version bump. While the Cloud libraries have moved to this new version, [`Google.Ads.GoogleAds`](https://www.nuget.org/packages/Google.Ads.GoogleAds) hasn't. This is because the Ads package uses grpc in a slightly more customized way than the Cloud packages, and needs additional testing and benchmarks to ensure all works well.

The error manifests when trying to create *any* service. The error looks like this:

```c#
Method not found: 'Void Google.Api.Gax.Grpc.ClientHelper..ctor(Google.Api.Gax.Grpc.ServiceSettingsBase)'.
```

In reality, this is an issue about failing to resolve a `Channel` implementation from `Grpc.Net.Client`, but since debug symbols are not present, it manifests as a `MethodNotFound` instead. 

For now, please downgrade the Cloud dependencies; we will prioritize this work for Q3 2022.

**Comment by scamner** [comment] 2022-06-30 01:18
Well, one step forward, but back to the original issue I was getting when I was using version 11 of the Google Ads library.

Getting this error...

Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1656551760.035000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1656551760.035000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")

**Comment by scamner** [comment] 2022-06-30 01:19
Oh, well, it looks like downgrading the libraries also wiped the settings from my config file, so let me get those back and try again. Tomorrow....

**Comment by scamner** [comment] 2022-06-30 01:35
Well, so much for tomorrow, I got the values, plugged them in and I still get that same error. I disconnected from my VPN to remove any possible issues with that and tried again, but still get the same.

**Comment by AnashOommen** [comment] 2022-08-03 18:43
Since this got resolved offline, I'll close this issue.

**Closed by AnashOommen** 2022-08-03 18:43 UTC
Labels: bug
