### ISSUE TITLE
Issue in Google ads api

### ISSUE THREAD

**Issue by boby-404** [googleads/google-ads-dotnet#260] opened 2021-01-28 06:48 UTC
Hi,
I am working on  google ads API in Dotnet
when fetching results g
![2021-01-28 12_05_48-Window](https://user-images.githubusercontent.com/78135342/106099768-3b53c600-6161-11eb-9f95-bbe3262caebb.png)
getting error like this

**Which version of the client library are you using?**

**Which version of .NET are you using?**

**Which operating system (Linux, Windows, ...) and version?**

**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]

**Expected result**

**Actual result**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**

**Comment by boby-404** [comment] 2021-01-28 07:05
Google.Ads.GoogleAds 6.1.0 > Google.Api.Gax.Grpc 3.2.0 > Google.Apis.Auth (>= 1.48.0 && < 2.0.0)

**Comment by AnashOommen** [comment] 2021-02-26 20:07
Hi,

If you can share a request ID or redacted call logs, it would be most helpful. Instructions are here: https://developers.google.com/google-ads/api/docs/client-libs/dotnet/logging

**Comment by AnashOommen** [comment] 2021-03-22 15:47
Closing this issue, since the logging instructions should give more hint about the root cause of this error. Please feel free to reopen if the issue persists.

**Closed by AnashOommen** 2021-03-22 15:47 UTC
Labels: bug
