### ISSUE TITLE
Upgrade from Nuget Package v11|Ads v10 to Nuget Package v14.2|Ads v12 cause INVALID_LOGIN_CUSTOMER_ID

### ISSUE THREAD

**Issue by tassosl** [googleads/google-ads-dotnet#479] opened 2023-01-05 19:35 UTC
Given the sunsetting of Ads v10 and the deprecation of Ads v11, I am upgrading our app to use version v14.2 of this nuget package and the v12 version of the Ads API. It used v11.0.0 of the nuget package with Ads version v10 before. The exact same API calls succeed in the old versions, but fail with an `INVALID_LOGIN_CUSTOMER_ID` error in the new versions. I enabled request logging and I noticed some differences between the request sent by the old package vs the new package, but unclear if those differences are related and/or responsible for the issue. (tokens and customer ids are the same across calls) 

1. `Host:` in the request with the new nuget package is not populated as it is in the old nuget package. Wondering if that could be the cause of the issue with the validation of the login-customer-id.
2. (Probably minor?) The various versions the tools have changed as shown in the `x-goog-api-client` header, interestingly the new nuget package has `gccl/2.1.0` instead of `gccl/11.0.0` in the old nuget package.

A couple of questions re: the usage of the nuget package
1. Is there something that changed in the nuget package that prevents the `Host:` from being populated in the request?
2. Anything that changed with the Desktop oAuth2 flow between those package versions?
3. Could the difference in grpc versions (2.41.0 before, 2.46.3 now) be related to the issue with the `Host:`?
4. Is downgrading of the gccl an issue or expected?

Code snippet of how our app invokes the API
```
var developerToken = "";
var mccAccountNumber = "";
var oauthClientId = "";
var oauthClientSecret = "";
var oauthRefreshToken = "";

var config = new GoogleAdsConfig
{
    DeveloperToken = developerToken,
    LoginCustomerId = mccAccountNumber,
    OAuth2Mode = OAuth2Flow.APPLICATION,
    OAuth2ClientId = oauthClientId,
    OAuth2ClientSecret = oauthClientSecret,
    OAuth2RefreshToken = oauthRefreshToken
};
var client = new GoogleAdsClient(config);
var service = client.GetService(GoogleServices.V12.GoogleAdsService);

var budget = new CampaignBudgetOperation();
// Set the properties on budget
var mutateOperations = new List<MutateOperation> { new MutateOperation { CampaignBudgetOperation = operation } };
var request = new MutateGoogleAdsRequest
{
    CustomerId = account.ImmutableId.ToString(),
    PartialFailure = true
};
request.MutateOperations.AddRange(mutateOperations);

var callSettings = client.ServiceContext.CallSettings;
client.MutateAsync(request, callSettings);
...
```

Request/Response logged from GoogleAds v14.2 / Ads API v12
```
GoogleAds.DetailedRequestLogs Information: 1: [2023 - 01 - 04 23: 34: 39Z] -
-------------- - BEGIN API CALL-------------- -

Request
------ -

Method Name: /google.ads.googleads.v12.services.GoogleAdsService/Mutate
Host:
Headers: {
    "x-goog-api-client": "gl-dotnet/5.0.0 gapic/14.2.0 gax/4.0.0+7489c236e0a5801d0f6e89bf1c23433f48521956 grpc/2.46.3 gccl/2.1.0 pb/3.21.5+638779f353731a0a04496bde20d14164684c3d93",
    "developer-token": "REDACTED",
    "login-customer-id": "REDACTED",
    "x-goog-request-params": "customer_id=REDACTED"
}
{
    "customerId": "REDACTED",
    "mutateOperations": [{
            "campaignBudgetOperation": {
                "create": {
                    "deliveryMethod": "STANDARD",
                    "period": "DAILY",
                    "name": "REDACTED",
                    "amountMicros": "1000000000",
                    "explicitlyShared": false
                }
            }
        }
    ],
    "partialFailure": true
}

Response
--------
Headers: {
    "request-id": "LYpklyZ85eUYCQG9OyuvlA",
    "date": "Wed, 04 Jan 2023 23:34:39 GMT",
    "alt-svc": "quic=\":443\"; ma=2592000",
    "google.ads.googleads.v12.errors.googleadsfailure-bin": "Cl4KA5AEAxJXVGhlIGxvZ2luIGN1c3RvbWVyIGlkIGhlYWRlciAnT3B0aW9uYWxbNDAzNzAwODc2OCwgNDAzNzAwODc2OF0nIGNvdWxkIG5vdCBiZSB2YWxpZGF0ZWQuEhZMWXBrbHlaODVlVVlDUUc5T3l1dmxB",
    "grpc-status-details-bin": "CAMSJVJlcXVlc3QgY29udGFpbnMgYW4gaW52YWxpZCBhcmd1bWVudC4awAEKRHR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmFkcy5nb29nbGVhZHMudjEyLmVycm9ycy5Hb29nbGVBZHNGYWlsdXJlEngKXgoDkAQDEldUaGUgbG9naW4gY3VzdG9tZXIgaWQgaGVhZGVyICdPcHRpb25hbFs0MDM3MDA4NzY4LCA0MDM3MDA4NzY4XScgY291bGQgbm90IGJlIHZhbGlkYXRlZC4SFkxZcGtseVo4NWVVWUNRRzlPeXV2bEE="
}

Fault: {
    "StatusCode": 3,
    "Details": "Request contains an invalid argument.",
    "RequestId": "LYpklyZ85eUYCQG9OyuvlA",
    "Failure": {
        "errors": [{
                "errorCode": {
                    "headerError": "INVALID_LOGIN_CUSTOMER_ID"
                },
                "message": "The login customer id header 'Optional[REDACTED, REDACTED]' could not be validated."
            }
        ],
        "requestId": "LYpklyZ85eUYCQG9OyuvlA"
    }
}
----------------END API CALL----------------
```

Request/Response logged from GoogleAds v11.0.0 / Ads API v10
```
GoogleAds.DetailedRequestLogs Verbose: 1: [2023 - 01 - 04 23: 43: 00Z] -
-------------- - BEGIN API CALL-------------- -

Request
------ -

Method Name: /google.ads.googleads.v10.services.GoogleAdsService/Mutate
Host: https: //googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-dotnet/5.0.0 gapic/11.0.0 gax/3.5.0+6cfcac416e08abe8a5d580f8d87095c9fdba577e grpc/2.41.0 gccl/11.0.0",
    "developer-token": "REDACTED",
    "login-customer-id": "REDACTED",
    "x-goog-request-params": "customer_id=REDACTED"
}
{
    "customerId": "REDACTED",
    "mutateOperations": [{
            "campaignBudgetOperation": {
                "create": {
                    "deliveryMethod": "STANDARD",
                    "period": "DAILY",
                    "name": "REDACTED",
                    "amountMicros": "1000000000",
                    "explicitlyShared": false
                }
            }
        }
    ],
    "partialFailure": true
}

Response
--------
Headers: {
    "content-disposition": "attachment",
    "request-id": "oK70D1SKOlLgLaUFyxoQXA",
    "date": "Wed, 04 Jan 2023 23:43:00 GMT",
    "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
}
{
    "mutateOperationResponses": [{
            "campaignBudgetResult": {
                "resourceName": "customers/REDACTED/campaignBudgets/REDACTED"
            }
        }
    ]
}
----------------END API CALL----------------
```

**Comment by davestitz** [comment] 2023-01-06 03:54
You may have already checked this but when you updated the Ads API Nuget package, the fresh placeholder values for the API connection are added into the app.config. Did you remove those empty values so your existing working values are use by the Ads Library? I know this sounds simple, but I have been caught by this a few times.

**Comment by tassosl** [comment] 2023-01-06 17:13
> You may have already checked this but when you updated the Ads API Nuget package, the fresh placeholder values for the API connection are added into the app.config. Did you remove those empty values so your existing working values are use by the Ads Library? I know this sounds simple, but I have been caught by this a few times.

We are configuring the library at [runtime](https://developers.google.com/google-ads/api/docs/client-libs/dotnet/configuration#configure_the_library_at_runtime) not via an `app.config` or a json config file. Is an `app.config` still needed in that case?

```
var config = new GoogleAdsConfig
{
    DeveloperToken = developerToken,
    LoginCustomerId = mccAccountNumber,
    OAuth2Mode = OAuth2Flow.APPLICATION,
    OAuth2ClientId = oauthClientId,
    OAuth2ClientSecret = oauthClientSecret,
    OAuth2RefreshToken = oauthRefreshToken
};
var client = new GoogleAdsClient(config);
var service = client.GetService(GoogleServices.V12.GoogleAdsService);
```

**Comment by AnashOommen** [comment] 2023-01-19 18:02
This is a duplicate of #481 and happens due to the difference in behaviour of `Grpc.Core` v/s `Grpc.Net.Client`. See https://github.com/googleapis/gax-dotnet/issues/672 for an explanation.

To get the old behaviour as a temporary workaround, you can do

```c#
config.UseGrpcCore = true;
```
A more permanent fix would be to construct a `CallSetting` from scratch instead of modifying `client.ServiceContext.CallSettings`. 

E.g. 

```c#
CancellationTokenSource source = new CancellationTokenSource(60 * 1000);
CallSettings callSettings = CallSettings.FromCancellationToken(source.Token);
await client.MutateAsync(request, callSettings);
```
I don't think it is trivial to consolidate the behaviour between Microsoft's and Google's implementation of grpc, but I'll continue exploring that option.

**Closed by AnashOommen** 2023-01-19 18:02 UTC
Labels: question
